[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 8080
  port = 8888
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
